apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: recipes-frontend
  name: recipes-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: recipes-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: recipes-frontend
    spec:
      containers:
      - name: recipes-frontend
        image: deckey/apps:recipes_1.0.4
        envFrom:
          - configMapRef:
              name: env
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: dbaccess
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbaccess
                key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
      restartPolicy: Always
      serviceAccountName: ""
      imagePullSecrets:
        - name: regaccess

--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    service: recipes-frontend
  name: recipes-frontend
spec:
  type: LoadBalancer
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: recipes-frontend
